---
- name: Include default vars of apache for {{qb_service}}
  include_vars:
    file: ../../apache/defaults/main.yml
    name: my_qb_defaults

- name: Remove apache config file for {{qb_service}}
  file:
    path: "{{my_qb_defaults.apache_site_dir}}/{{qb_service}}.conf"
    state: absent
  register: apache_st

- name: Restart apache for {{qb_service}}
  systemd:
    name: "{{my_qb_defaults.apache_pkg_name}}"
    state: restarted
  when: apache_st is changed
