---
- name: Include default vars of nginx for {{qb_service}}
  include_vars:
    file: ../../nginx/defaults/main.yml
    name: my_nginx_defaults

- name: Remove nginx config file for {{qb_service}}
  file:
    path: "{{my_nginx_defaults.nginx_dir}}/conf.d/{{qb_service}}.conf"
    state: absent
  register: nginx_st

- name: Restart nginx for {{qb_service}}
  systemd:
    name: nginx
    state: restarted
  when: nginx_st is changed
