---
- name: Create group account for qb
  group:
    name: "{{qbroker_group}}"
    state: present

- name: Create user account for qbadm
  user:
    name: "{{qbroker_user}}"
    comment: QBroker
    group: "{{qbroker_group}}"
    state: present
    shell: /bin/bash
    home: "{{qbroker_dir}}"
    createhome: no

- name: Create dirs of /var/cache/ansible and /opt
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /var/cache/ansible
    - /opt

- name: Create subdirs for qbroker
  file:
    path: "{{qbroker_dir}}/{{item}}"
    state: directory
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0775
  with_items:
    - agent
    - bin
    - cfg
    - flow
    - lib
    - init.d/inactive
    - jndi
    - templates

- name: Get stats of qblib-x.y.z.tgz
  stat:
    path: "/var/cache/ansible/{{qbroker_shared_lib}}"
    get_md5: no
    get_checksum: no
  register: st_qb_tarball

- name: Get the tarball via s3
  command: "aws s3 --region {{region|default('us-east-2')}} cp {{qbroker_repo_url}}/{{qbroker_shared_lib}} /var/cache/ansible/"
  when: not st_qb_tarball.stat.exists and qbroker_repo_url|regex_search('^s3:')
  register: new_archive_qb1

- name: Get the tarball via http
  get_url:
    url: "{{qbroker_repo_url}}/{{qbroker_shared_lib}}"
    dest: /var/cache/ansible/
    validate_certs: "{{qbroker_validate_certs}}"
  when: not st_qb_tarball.stat.exists and not qbroker_repo_url|regex_search('^s3:')
  register: new_archive_qb2

- name: Get stats of /opt/qbroker/lib
  stat:
    path: "{{qbroker_dir}}/lib"
    get_md5: no
    get_checksum: no
  register: st_qbroker_lib

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{qbroker_shared_lib}}"
    dest: "{{qbroker_dir}}"
    remote_src: yes
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
  when: new_archive_qb1 is changed or new_archive_qb2 is changed or not st_qbroker_lib.stat.exists

- name: Template of QClient.sh
  template:
    src: QClient.sh.j2
    dest: "{{qbroker_dir}}/bin/QClient.sh"
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0775
  vars:
    java: "{{qbroker_java}}"
    dir: "{{qbroker_dir}}"
    jar_files: "{{qbroker_qclient_jars}}"

- name: Copy shared files
  copy:
    src: "{{item}}"
    dest: "{{qbroker_dir}}/cfg/{{item}}"
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0664
  with_items:
    - hb_pub.json
    - hb_put.json
    - unsub.json
    - selfsigned.jks
