---
- name: Get stats of {{item}}
  stat:
    path: "/var/cache/ansible/{{item}}"
    get_md5: no
    get_checksum: no
  register: st_ex_jar

- name: Get the {{item}} via s3
  command: "aws s3 --region {{region|default('us-east-2')}} cp {{qbroker_repo_url}}/extra/{{item}} /var/cache/ansible/"
  when: not st_ex_jar.stat.exists and qbroker_repo_url|regex_search('^s3:')
  register: new_jar_ex1

- name: Get the {{item}} via http
  get_url:
    url: "{{qbroker_repo_url}}/extra/{{item}}"
    dest: /var/cache/ansible/
    validate_certs: "{{qbroker_validate_certs}}"
  when: not st_ex_jar.stat.exists and not qbroker_repo_url|regex_search('^s3:')
  register: new_jar_ex2

- name: Get stats of {{item}}
  stat:
    path: "{{qbroker_dir}}/lib/{{item}}"
    get_md5: no
    get_checksum: no
  register: st_extra_jar

- name: Copy {{item}}
  copy:
    src: "/var/cache/ansible/{{item}}"
    dest: "{{qbroker_dir}}/lib/"
    remote_src: yes
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
  when: new_jar_ex1 is changed or new_jar_ex2 is changed or not st_extra_jar.stat.exists
