---
- include: common.yml

- include: extra_jar.yml
  when: qbroker_extra_jar is defined

- include: log.yml
  when: qbroker_logdir != None

- include: webapp.yml
  when: qbroker_service_id != None and qbroker_webapp_context != None
