---
- include: common.yml

- include: log.yml
  when: qbroker_logdir != None

- include: security_plugin.yml
  when: qbroker_security_plugin != None

- include: instance.yml
  when: qbroker_service_id != None and qbroker_webapp_context == None 

- include: webapp.yml
  when: qbroker_service_id != None and qbroker_webapp_context != None
