---
- name: Get stats of security plugin
  stat:
    path: "/var/cache/ansible/{{qbroker_security_plugin}}"
    get_md5: no
    get_checksum: no
  register: st_qb_security_plugin

- name: Get the security plugin
  command: "aws s3 --region {{region|default('us-east-2')}} cp {{qbroker_repo_url}}/{{qbroker_security_plugin}} /var/cache/ansible/"
  when: not st_qb_security_plugin.stat.exists

- name: Copy security plugin
  copy:
    src: "/var/cache/ansible/{{qbroker_security_plugin}}"
    dest: "{{qbroker_dir}}/lib/"
    remote_src: yes
    force: no
    owner: "{{qbroker_user}}"
    group: "{{qbroker_group}}"
    mode: 0644
